### ISSUE TITLE
Breadcrumbs::render() not showing

### ISSUE THREAD

**Issue by monder007** [creitive/laravel5-breadcrumbs#4] opened 2017-05-11 06:19 UTC
Hi
I've setup this plugin as specified and added some crumbs but when I render in the blade template, nothing is output.

If I do dd in the controller on the $this->breadcrumb variable it outputs my crumbs but just doesn't do anything in the view.

It on laravel 5.4

Any ideas?

**Comment by levacic** [comment] 2017-05-19 06:17
Hi @monder007, sorry for the slowish reply.

I've just tested it out on a fresh Laravel 5.4 installation (using the facade, so as to avoid the rest of the setup) and it works as intended.

```sh
$ composer create-project --prefer-dist laravel/laravel laravel54-breadcrumbs-test
$ cd laravel54-breadcrumbs-test
$ composer require creitive/laravel5-breadcrumbs
```

I added `Creitive\Breadcrumbs\BreadcrumbsServiceProvider::class` as a service provider and `'Breadcrumbs' => Creitive\Breadcrumbs\Facades\Breadcrumbs::class` as a facade in `config/app.php`.

Within `routes/web.php`, I changed the default route to this:

```php
Route::get('/', function () {
    Breadcrumbs::addCrumb('Home', '/');
    Breadcrumbs::addCrumb('Foo', 'foo');
    Breadcrumbs::addCrumb('Bar', 'bar');

    return view('welcome');
});
```

In `resources/views/welcome.blade.php` I added `{!! Breadcrumbs::render() !!}` after the opening body tag.

After running `php artisan serve` and opening `http://127.0.0.1:8000`, the breadcrumbs are successfully rendered, and visible in the source code:

```html
<ul itemscope itemtype="http://schema.org/BreadcrumbList" class="breadcrumbs"><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" ><a itemprop="item" href="/"><span itemprop="name">Home</span></a><meta itemprop="position" content="1" /> <span class="divider">/</span></li><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" ><a itemprop="item" href="/foo"><span itemprop="name">Foo</span></a><meta itemprop="position" content="2" /> <span class="divider">/</span></li><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="active"><span itemprop="name">Bar</span><meta itemprop="position" content="3" /></li></ul>
```

It works as it's supposed to work (as far as I can tell), so I'm closing this issue.

If you need some additional help with setting it up, feel free to respond with more information, but I don't think there is a problem with the package itself (also, how you actually manipulate the breadcrumbs in your code and how you pass them into your views is probably not in the scope of the package itself, although we do provide some helpful tips about that).

Hope this helps!

**Closed as completed by levacic** 2017-05-19 06:17 UTC
